services:
  postgres:
    image: postgres:16
    container_name: eve_postgres
    ports:
      - "12920:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eve_api
    ports:
      - "12922:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eve_frontend
    ports:
      - "12921:3000"
    depends_on:
      - api
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.tundragon.space
    env_file:
      - ./frontend/.env.local
    restart: always

volumes:
  postgres_data:
