services:
  postgres:
    image: postgres:16
    container_name: eve_postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: eve
      POSTGRES_USER: eve
      POSTGRES_PASSWORD: eve
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eve_api
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=eve
      - DB_PASSWORD=eve
      - DB_NAME=eve
    restart: always

  caddy:
    image: caddy:2
    container_name: eve_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
    restart: always

volumes:
  caddy_data:
  caddy_config: